#!/usr/bin/env python3
"""
Fetch and cache text from https://www.yaleconsulting.org for Ollama outreach recommendations.
Writes data/yucg_website_corpus.txt with source URLs per section (verifiable citations).

Usage (from repo root):
  python scripts/build_yucg_ollama_context.py
  python scripts/build_yucg_ollama_context.py --force
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

import httpx

try:
    from bs4 import BeautifulSoup
except ImportError:
    print("Install beautifulsoup4: pip install beautifulsoup4", file=sys.stderr)
    raise

REPO_ROOT = Path(__file__).resolve().parents[1]
CACHE_DIR = REPO_ROOT / "data" / ".yucg_cache"
OUTPUT_PATH = REPO_ROOT / "data" / "yucg_website_corpus.txt"

# label, URL — Wix site paths used by YUCG
PAGE_TARGETS: list[tuple[str, str]] = [
    ("home", "https://www.yaleconsulting.org/"),
    ("about", "https://www.yaleconsulting.org/aboutus"),
    ("services", "https://www.yaleconsulting.org/services"),
    ("contact", "https://www.yaleconsulting.org/contact"),
    ("projects", "https://www.yaleconsulting.org/projects"),
    ("blog", "https://www.yaleconsulting.org/blog"),
    ("recent_work", "https://www.yaleconsulting.org/our-work"),
]

USER_AGENT = "YUCG-Outreach-Context-Builder/1.0 (+local dev; contact: yucg-outreach-coordinator)"


def _cache_path(url: str) -> Path:
    digest = hashlib.sha256(url.encode()).hexdigest()[:16]
    return CACHE_DIR / f"{digest}.html"


def fetch_page(client: httpx.Client, url: str, *, force: bool) -> str:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    cache = _cache_path(url)
    if cache.is_file() and not force:
        return cache.read_text(encoding="utf-8", errors="replace")

    r = client.get(url, follow_redirects=True)
    r.raise_for_status()
    html = r.text
    cache.write_text(html, encoding="utf-8")
    return html


def html_to_text(html: str) -> str:
    soup = BeautifulSoup(html, "html.parser")
    for tag in soup(["script", "style", "noscript", "svg"]):
        tag.decompose()
    text = soup.get_text(separator="\n")
    lines = [ln.strip() for ln in text.splitlines()]
    lines = [ln for ln in lines if ln and len(ln) > 1]
    # Drop very repetitive nav noise
    deduped: list[str] = []
    seen: set[str] = set()
    for ln in lines:
        key = ln.lower()
        if key in seen:
            continue
        seen.add(key)
        deduped.append(ln)
    blob = "\n".join(deduped)
    blob = re.sub(r"\n{3,}", "\n\n", blob)
    return blob.strip()


def build_corpus(*, force: bool = False) -> str:
    sections: list[str] = []
    sections.append(
        "# YUCG Website Corpus\n"
        "# Generated by scripts/build_yucg_ollama_context.py — each section cites its source URL.\n"
    )

    with httpx.Client(
        timeout=30.0,
        headers={"User-Agent": USER_AGENT},
    ) as client:
        for label, url in PAGE_TARGETS:
            try:
                html = fetch_page(client, url, force=force)
                text = html_to_text(html)
                if len(text) < 80:
                    sections.append(
                        f"=== {label} (sparse) ===\nSource: {url}\n"
                        f"---\n[Page fetched but little extractable text — Wix may require JS.]\n"
                    )
                    continue
                sections.append(f"=== {label} ===\nSource: {url}\n---\n{text}\n")
            except httpx.HTTPError as e:
                sections.append(
                    f"=== {label} (fetch failed) ===\nSource: {url}\n---\n[Error: {e}]\n"
                )

    return "\n".join(sections).strip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Build YUCG website corpus for Ollama outreach AI")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-fetch all pages (ignore HTML cache)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help=f"Output corpus path (default: {OUTPUT_PATH})",
    )
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    corpus = build_corpus(force=args.force)
    args.output.write_text(corpus, encoding="utf-8")
    print(f"Wrote {len(corpus)} chars to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
